services:
  

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: '192.168.68.52 -> http://192.168.68.52:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  database:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
    volumes:
      - db:/var/lib/db
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql

  
  app:
    depends_on:
     - database
    build: .
    restart: unless-stopped
    ports: 
      - 8080:8080
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - jwtSecret=$jwtSecret

volumes:
  db: