services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file: ./.env
    depends_on:
      - certbot
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    network_mode: host
    command: certonly --standalone --preferred-challenges http --email nave1616@hotmail.com --agree-tos -d nave.autos --non-interactive --keep-until-expiring
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  database:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/db
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: ./.env
    environment:
      - MYSQL_HOST=database

volumes:
  db:
