# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container:
        image: alpine:latest
        options: --user root
    steps:
    - run: sudo apt update 
    - run: sudo apt install Node.Js npm
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run scss

